
export const USER_RECIEVED = 'USER_RECIEVED';
export const  USER_CREATED = 'USER_CREATED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const CURRENT_USER_RECIEVED = 'CURRENT_USER_RECIEVED';
